### ISSUE TITLE
Q2 위장

### ISSUE THREAD

**Issue by Incheol-Jung** [GANGNAM-JAVA/JAVA-STUDY#12]
https://programmers.co.kr/learn/courses/30/lessons/42578

**Comment by weed0124** [comment]
[Q2.위장]-두용선#16

**Comment by weed0124** [comment]
> https://programmers.co.kr/learn/courses/30/lessons/42578

[Q2.위장]-두용선

**Comment by weed0124** [comment]
[Q2-위장]-두용선 #16

**Comment by Incheol-Jung** [comment]
이슈 완료되어 종료합니다.
